### PR TITLE
Fix ASIC check on Non-SONiC leaf fanout

### PR DESCRIPTION
**Pull request by bingwang-ms**
### Description of PR

Summary:
This PR is to fix an issue brought by PR https://github.com/sonic-net/sonic-mgmt/pull/12931.
```
>       raise AttributeError(
            "'%s' object has no attribute '%s'" % (self.__class__, module_name)
            )
E       AttributeError: '<class 'tests.common.devices.eos.EosHost'>' object has no attribute 'facts'
```
The issue is because if the leaf fanout is not running SONiC, then the host has no attribute `facts`.
This PR addressed the issue by checking OS first and the ASIC check is bypassed if OS is not SONiC.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311

#### What is the motivation for this PR?
This PR is to fix an issue caused by PR https://github.com/sonic-net/sonic-mgmt/pull/12931.

#### How did you do it?
This PR addressed the issue by checking OS first and the ASIC check is bypassed if OS is not SONiC.

#### How did you verify/test it?
The change is verified on a physical testbed **without** leaf fanout running SONiC.
```
collected 1 item                                                                                                                                                                                      

iface_loopback_action/test_iface_loopback_action.py::test_loopback_action_basic  ^HPASSED                                                                                                          [100%]
```
#### Any platform specific information?
Mellanox platform specific.

#### Supported testbed topology if it's a new test case?
Not a new test case.

### CODE REVIEW

**Review by yanmo96 — APPROVED** [review]
LGTM
