### PR TITLE
Fix syntax issue in TunnelDscpToPgMapping

### PR DESCRIPTION
**Pull request by bingwang-ms**
### Description of PR

Summary:
This PR is to fix a syntax error in `TunnelDscpToPgMapping`.
The error message is as below.
```
"ERROR: sai_qos_tests.TunnelDscpToPgMapping", "----------------------------------------------------------------------", "Traceback (most recent call last):", "  File "saitests/py3/sai_qos_tests.py", line 1192, in runTest", "    self.client, asic_type, port_list['src'][src_port_id])", "AttributeError: 'TunnelDscpToPgMapping' object has no attribute 'client'", "", "----------------------------------------------------------------------", "Ran 1 test in 20.752s", "", "FAILED (errors=1)"], "stdout": "Using packet manipulation module: ptf.packet_scapy\n\n******************************************
ATTENTION: SOME TESTS DID NOT PASS!!!
The following tests errored:
TunnelDscpToPgMapping
******************************************", "stdout_lines": ["Using packet manipulation module: ptf.packet_scapy", "", "******************************************", "ATTENTION: SOME TESTS DID NOT PASS!!!", "", "The following tests errored:", "TunnelDscp
```
It's a regression caused by PR https://github.com/sonic-net/sonic-mgmt/pull/9780
### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
This PR is to fix a syntax error in `TunnelDscpToPgMapping`.

#### How did you do it?
Fix the variable name.

#### How did you verify/test it?
The change is verified on a physical dualtor testbed. Test can pass after this change.
```
collected 1 item                                                                                                                                                                                      

qos/test_tunnel_qos_remap.py::test_tunnel_decap_dscp_to_pg_mapping  ^H ^HPASSED                                                                                                                       [100%] ^H ^H

```
#### Any platform specific information?
No.

#### Supported testbed topology if it's a new test case?
Not a new test case.

### CODE REVIEW

**Review by yxieca — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@StormLiangMS Can you please help to cherry-pick?
