### ISSUE TITLE
Bug: `snappi_tests/pfc/warm_reboot/test_pfc_pause_lossless_warm_reboot.py` is failing

### ISSUE THREAD

**Issue by rajkumar1-arista** [sonic-net/sonic-mgmt#18933]
### Is it platform specific

generic

### Importance or Severity

Medium

### Description of the bug

`snappi_tests/pfc/warm_reboot/test_pfc_pause_lossless_warm_reboot.py` is failing with `TypeError: reboot() got an unexpected keyword argument 'plt_reboot_ctrl_overwrite'`

Regression due to #16031

in `common/snappi_tests/traffic_generation.py` `reboot()` is still using the removed argument `plt_reboot_ctrl_overwrite` that is resulting in failure.

### Steps to Reproduce

run `snappi_tests/pfc/warm_reboot/test_pfc_pause_lossless_warm_reboot.py`

### Actual Behavior and Expected Behavior

Test is expected to pass without above failure.

### Relevant log output

```shell

```

### Output of `show version`

```shell

```

**Comment by yxieca** [comment]
Fix has been merged.
