### ISSUE TITLE
Not able to run platform_tests because of error in conditional mark

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-mgmt#7940]
**Description**

Noticed the following error when running platform_tests with T2 topo:
```
INTERNALERROR> Traceback (most recent call last):                                                                                                                                                                                                    
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/main.py", line 206, in wrap_session                                                                                                                                            
INTERNALERROR>     session.exitstatus = doit(config, session) or 0                                                                                                                                                                                   
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/main.py", line 259, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/main.py", line 498, in perform_collect
INTERNALERROR>     session=self, config=self.config, items=items
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/data/tests/common/plugins/conditional_mark/__init__.py", line 544, in pytest_collection_modifyitems
INTERNALERROR>     conditions_logical_operator = mark_details.get('conditions_logical_operator', 'AND').upper()
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'get'
```

**Steps to reproduce the issue:**
1. Run platform_tests with T2 topo.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by ysmanman** [comment]
The error seems introduced in https://github.com/sonic-net/sonic-mgmt/pull/7802.  The indentation is missing in the following lines https://github.com/sonic-net/sonic-mgmt/blob/master/tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml#L730-L731

**Comment by ysmanman** [comment]
Add @arlakshm @wenyiz2021 for visibility.

**Comment by bingwang-ms** [comment]
Fixed in https://github.com/sonic-net/sonic-mgmt/pull/7941
