### PR TITLE
[202511] Fix UT2 golden_config_db AttributeError for bgp_confd_asn/peers (#27582)

### LINKED ISSUE #27582: Bug: T2 single-node min/max topology deployment fails during golden_config_db generation on 202511
### Is it platform specific

generic

### Importance or Severity

Critical

### Description of the bug

After sonic-mgmt PR #26241 merged into the 202511 branch, deployments using T2 single-node min/max topologies fail at the Generate golden_config_db.json task.

PR #26241 added generate_ut2_golden_config_db(), which references:
```
self.bgp_confd_asn
self.bgp_confd_peers
```

However, these attributes are not defined by GenerateGoldenConfigDBModule in the 202511 branch as of now. Their module arguments, instance initialization, and Ansible task inputs were originally introduced by PR #22417 which has not been backported to 202511 yet.

### Steps to Reproduce

When deploying t2 min or max topo with 202511 branch
```
cd /data/ansible
  ./testbed-cli.sh -k ceos add-topo ardut password.txt -l server_1 -vvv
  ./testbed-cli.sh deploy-mg ardut lab password.txt -vvv
```

An AttributeError when generating golden_config_db.json is seen during deployment
```
TASK [Generate golden_config_db.json] ************************************************************************************************************************
task path: /data/ansible/config_sonic_basedon_testbed.yml:741
Using module file /data/ansible/library/generate_golden_config_db.py
Pipelining is enabled.
<10.248.88.159> ESTABLISH SSH CONNECTION FOR USER: admin
<10.248.88.159> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=180s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=40 -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=60 -o 'ControlPath="/sonic-mgmt/cp/ansible-ssh-%h-%p-%r"' -o Number
OfPasswordPrompts=1 10.248.88.159 '/bin/sh -c '"'"'sudo -H -S -p "[sudo via ansible, key=dmxlqydvivbnggcsgdjsnhukvplfktce] password:" -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dmxlqydvivbnggcsgdjsnhukvplfktce ; /usr/bin/python3.13'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<10.248.88.159> Escalation succeeded
<10.248.88.159> (1, b'{"failed": true, "exception": {"event": {"msg": "\'GenerateGoldenConfigDBModule\' object has no attribute \'bgp_confd_asn\'", "__ansible_type": "Event"}, "__ansible_type": "ErrorSummary"}}\n', b'')
<10.248.88.159> Failed to connect to the host via ssh:
[ERROR]: Task failed: Module failed: 'GenerateGoldenConfigDBModule' object has no attribute 'bgp_confd_asn'
Origin: /data/ansible/config_sonic_basedon_testbed.yml:741:9

739         when: "'t2_single_node' in topo or 'lt2' in topo or 'ft2' in topo"
740
741       - name: Generate golden_config_db.json
            ^ column 9

fatal: [qzd368]: FAILED! => {
    "changed": false,
    "msg": "Task failed: Module failed: 'GenerateGoldenConfigDBModule' object has no attribute 'bgp_confd_asn'"
}

PLAY RECAP ***************************************************************************************************************************************************
qzd368                     : ok=74   changed=7    unreachable=0    failed=1    skipped=53   rescued=0    ignored=0
```

### Actual Behavior and Expected Behavior

**Root cause**

PR #26241 introduced a runtime dependency on part of the BGP confederation support from PR #22417 without bringing that dependency into the 202511 branch.

**Resolution requires a support decision**

One of the following is needed:
  - If want BGP confederation support to be added to sonic-mgmt in 202511 - then backport the required changes from PR #22417
  - If we do not want this support in sonic-mgmt, then we propose reverting PR #26241.

Proposal to revert PR #26241 restores deployment behavior, but the final fix depends on whether BGP confederation support is intended for 202511.

### Relevant log output

```shell

```

### Output of `show version`

```shell

```

### Attach files (if any)

_No response_

### PR DESCRIPTION
**Pull request by YatishSVC**
### Description of PR

Fixes #27582.

Deploying **T2 single-node min/mix (and `lt2`/`ft2`) topologies on 202511** fails at the `Generate golden_config_db.json` task with:

```
'GenerateGoldenConfigDBModule' object has no attribute 'bgp_confd_asn'
```

**Root cause:** PR #26241 (cherry-pick of #24415) brought `generate_ut2_golden_config_db()` onto 202511. That method reads `self.bgp_confd_asn` / `self.bgp_confd_peers`, which are defined by PR #22417 (`argument_spec` + `__init__` + Ansible task inputs). #22417 was **never backported to 202511**, so the consumer landed without its provider and the attribute lookup raises `AttributeError` at deploy time. (master is unaffected — #22417 merged there before the consumers.)

**Fix:** define `bgp_confd_asn` / `bgp_confd_peers` in the module `argument_spec` (default `None`) and assign them in `__init__`, mirroring #22417. This is the minimal, faithful slice — it does **not** pull in the broader BGP-confederation test infra (intentionally absent from 202511, see #25188). When confed isn't configured (the 202511 default), the existing `if self.bgp_confd_asn and self.bgp_confd_peers:` guards simply evaluate to `None` and are skipped, so no `CONFED` block is emitted. If confed inputs are ever supplied, the rendering path still works.

### Type of change

- [x] Bug fix

### Back port request

- [ ] 202311
- [ ] 202405
- [ ] 202411
- [ ] 202505
- [ ] 202511
- [ ] 202512
- [ ] 202605

N/A — this change targets the 202511 branch directly (the regression is 202511-only).

#### What is the motivation for this PR?

Unblock T2 single-node / `lt2` / `ft2` deployments on 202511 that regressed after #26241 merged.

#### How did you do it?

Added the two missing module parameters and their `__init__` assignments (a 4-line subset of #22417). No `config_sonic_basedon_testbed.yml` change is required — with `default=None`, the params resolve to `None` when the task does not pass them, and the confed guards no-op.

#### How did you verify/test it?

Isolated the exact failing code path (`generate_ut2_golden_config_db()`), stubbing the minigraph/macsec helpers, and drove it against the pre-fix and post-fix module across three scenarios:

| Scenario | File | confed inputs | Result |
|---|---|---|---|
| 1 — reproduce the bug | 202511 pre-fix | none | `AttributeError: 'GenerateGoldenConfigDBModule' object has no attribute 'bgp_confd_asn'` |
| 2 — deploy path (default) | this PR | none | OK — no crash, valid JSON, **no** `CONFED` block emitted |
| 3 — forward compatibility | this PR | asn+peers set | OK — no crash, valid JSON, `BGP_DEVICE_GLOBAL.CONFED` rendered |

Raw output:

```
==== SCENARIO 1: OLD 202511 (pre-fix), no confed ====
RESULT: AttributeError -> 'GenerateGoldenConfigDBModule' object has no attribute 'bgp_confd_asn'

==== SCENARIO 2: NEW fixed, no confed (the 202511 deploy path) ====
RESULT: OK (no crash); valid JSON; CONFED_rendered=False

==== SCENARIO 3: NEW fixed, WITH confed ====
RESULT: OK (no crash); valid JSON; CONFED_rendered=True
```

`py_compile` and `flake8 --max-line-length=120` are clean on the changed file.

### CODE REVIEW

**Comment by YatishSVC** [comment]
Closing in favor of the full #22417 backport #27699, which fixes the deploy regression AND brings BGP confederation support to 202511. This minimal 4-line variant is redundant now.
