### PR TITLE
[platform] Add missing consistency_checker_provider fixture to test_fast_reboot_from_other_vendor

### PR DESCRIPTION
**Pull request by rustiqly**
### Description of PR
[agent]
Add the missing `consistency_checker_provider` fixture parameter to `test_fast_reboot_from_other_vendor`.

The test body passes `consistency_checker_provider` to `get_advanced_reboot()`, but the fixture was never declared as a test parameter, causing:
```
AttributeError: 'FixtureFunctionDefinition' object has no attribute 'is_consistency_check_supported'
```

All other reboot tests (`test_fast_reboot`, `test_warm_reboot`, etc.) already include this fixture in their signatures. This was introduced in PR #16877 which added the fixture to the function body but not the parameters.

Fixes: #22795

### Type of change
- [x] Bug fix

### How did you test it?
```
AST parse: OK
Verified consistency_checker_provider is now in function signature (line 105)
and matches the reference in get_advanced_reboot() call (line 116)
```

### CODE REVIEW

**Review by yxieca — APPROVED** [review]
AI agent on behalf of Ying. Reviewed; no issues found.
