### PR TITLE
[sonic-mgmt] Fix snappi_tests/test_snappi.py failure

### PR DESCRIPTION
**Pull request by vkjammala-arista**
### Description of PR

Summary: Fix snappi_tests/test_snappi.py failure
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/18896

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] New Test case
    - [ ] Skipped for non-supported platforms
- [ ] Test case improvement

### Back port request
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405
- [ ] 202411
- [x] 202505

#### What is the motivation for this PR?
Test is failing with
```
============================================================================================== short test summary info ===============================================================================================
FAILED snappi_tests/test_snappi.py::test_snappi - AttributeError: 'Api' object has no attribute 'transmit_state'
====================================================================================== 1 failed, 1 warning in 595.57s (0:09:55) ==================================================================
```
#### How did you do it?
Updating test to adopt to newer version of snappi introduced by https://github.com/sonic-net/sonic-buildimage/pull/22345 and fix is similar to https://github.com/sonic-net/sonic-mgmt/pull/18523

#### How did you verify/test it?
Test is passing with the test.

### CODE REVIEW

**Review by anders-nexthop — APPROVED** [review]
This is a straightforward fix for a simple regression and can be merged right away.

@yxieca for viz

**Comment by yxieca** [comment]
@sdszhang @developfast this is an SNAPPI API change? If we expected generic API could change, then should we have an adapter layer to work with different versions?

**Comment by developfast** [comment]
there are way too many snappi APIs to create an adapter layer based on snappi version in this version - looks like this one file was overlooked during the main snappi api update change 

@sdszhang will be more familiar

**Comment by sdszhang** [comment]
> @sdszhang @developfast this is an SNAPPI API change? If we expected generic API could change, then should we have an adapter layer to work with different versions?

Hi @yxieca, yes. This is due to the recent snappi API change in  https://github.com/sonic-net/sonic-mgmt/pull/17914 and https://github.com/sonic-net/sonic-buildimage/pull/22345 . We should consider an adapter layer to avoid breaking changes, maybe not in this version update, but when next API change comes.
@kamalsahu0001 @selldinesh for viz.

**Review by sdszhang — APPROVED** [review]
lgtm
