### PR TITLE
Revert "[202511][cherry-pick] update golden_config_db rendering for UT2 

### PR DESCRIPTION
**Pull request by YatishSVC**
### Description of PR

Alternative resolution for #27582 (see also the forward-fix #27697 — **only one of the two should be merged**).

This reverts #26241 *"[202511][cherry-pick] update golden_config_db rendering for UT2 (#24415)"*, which regressed 202511: it added `generate_ut2_golden_config_db()` reading `self.bgp_confd_asn` / `self.bgp_confd_peers`, but the provider PR #22417 that defines those attributes was never backported to 202511. As a result, deploying **T2 single-node min/mix (and `lt2`/`ft2`) topologies** fails at the `Generate golden_config_db.json` task with:

```
'GenerateGoldenConfigDBModule' object has no attribute 'bgp_confd_asn'
```

Reverting #26241 restores the pre-regression deployment behavior on 202511 by removing the UT2 golden_config rendering that depends on the missing confed plumbing.

### Which fix to take?

- **If the UT2 golden_config rendering is wanted on 202511:** merge the forward-fix **#27697** instead (adds the 4 missing `argument_spec` + `__init__` definitions; keeps the feature, confed guards no-op when not configured). Do **not** merge this revert.
- **If the feature is not needed on 202511 right now:** merge this revert to unblock deployment immediately.

### Type of change

- [x] Bug fix (revert)

### Back port request

- [ ] 202311
- [ ] 202405
- [ ] 202411
- [ ] 202505
- [ ] 202511
- [ ] 202512
- [ ] 202605

N/A — targets 202511 directly (202511-only regression).

#### How did you verify/test it?

- Clean `git revert` of the squash commit `018533ec9` (#26241); 2 files changed, −137 lines.
- After revert, `generate_golden_config_db.py` contains **no** references to `generate_ut2_golden_config_db` or `bgp_confd_*` (grep count 0), and `py_compile` is clean.
- The same isolated harness used for #27697 confirms the pre-regression module has no `bgp_confd_asn` code path to fail on.

### CODE REVIEW

**Comment by YatishSVC** [comment]
## Physical-DUT validation

Validated on the **same physical T2 single-node DUT** (`topo: t2_single_node_max_64p`, single-ASIC) used for the forward-fix, running the real `generate_golden_config_db` Ansible module end-to-end on hardware. Confirms the revert also clears the regression (by removing the `generate_ut2` path that consumed the undefined attribute).

| Case | Module result | `golden_config_db.json` |
|---|---|---|
| OLD 202511 (pre-fix) | `FAILED!` — `AttributeError: … has no attribute 'bgp_confd_asn'` (`generate_ut2_golden_config_db`, line 772) | not written |
| **This revert** | `Success to generate golden_config_db.json` | generated with the ut2/confed path removed (`BGP_DEVICE_GLOBAL` absent) — i.e. the pre-regression behavior |

Raw output (hostnames elided):

```
=== CASE: OLD 202511 (pre-fix) ===
<dut> | FAILED! => AttributeError: 'GenerateGoldenConfigDBModule' object has no attribute 'bgp_confd_asn'

=== CASE: REVERT (this PR) ===
"msg": "Success to generate golden_config_db.json"
BGP_DEVICE_GLOBAL_present=False  CONFED=None
```

Note: this revert restores the pre-#26241 behavior (no UT2 golden_config rendering for `t2_single_node`), so it unblocks deployment but does **not** provide BGP confederation support. If confed support on 202511 is desired, use the full backport #27699 instead.

**Comment by YatishSVC** [comment]
## Validation: full `bgp/` suite on a physical T2 DUT (revert vs `master`)

This PR reverts #26241 on 202511 to fix the `generate_golden_config_db` `AttributeError` regression tracked in #27582. To confirm the fix is correct **and** introduces no new BGP regressions, I ran the **entire `bgp/` test suite on a physical single‑ASIC VOQ T2 chassis testbed** — once with this revert branch (public 202511 + this PR) and once with public `master` as an apples‑to‑apples control.

### Deploy / config generation
- `deploy-mg` succeeded (`failed=0`); all BGP sessions established (64/64, both address families).
- **0** occurrences of `'GenerateGoldenConfigDBModule' object has no attribute 'bgp_confd_asn'` (the #27582 signature) — the regression is gone.
- `bgp/test_bgp_fact.py::test_bgp_facts` **PASSED** on the DUT.

### Full `bgp/` suite results

| | This PR (revert, 202511) | `master` (control) |
|---|---|---|
| passed | 3 | 20 |
| failed | 3 | 3 |
| errors | 32 | 26 |
| skipped | 134 | 210 |
| golden_config `AttributeError` | **0** | **0** |

(`master` shows more passed/skipped simply because the newer tree carries more `bgp/` cases than 202511.)

### The failures/errors are branch‑independent (testbed infra, not this change)
- **Failed identically on both branches:** `test_bgp_peer_shutdown`, `test_bgp_update_timer_session_down`.
- `master`'s only additional failure — `test_prefix_list_suppress.py::TestAnchorPrefixRegression` — lives in a test file that **does not exist on 202511**, so it cannot be caused by this revert.
- **Errored files are the same set on both branches:** `test_bgp_authentication`, `test_bgp_router_id`, `test_bgp_session_flap`, `test_ipv6_nlri_over_ipv4`, `test_passive_peering`, `test_prefix_list`, `test_seq_idf_isolation`, `test_startup_tsa_tsb_service`. Root causes are testbed‑infra (SSH auth to neighbor VMs and a pre‑existing fixture `UnboundLocalError`) — none touch config generation.

### Conclusion
This revert fixes the deploy‑time regression (0 `AttributeError`s, healthy 64/64 BGP), and **every** failure/error observed on this branch also occurs on `master` → the change introduces no new BGP regressions.

**Review by arista-nwolfe — APPROVED** [review]

**Review by saravanan-nexthop — APPROVED** [review]
