### ISSUE TITLE
Bug: test_subnet_decap calls removed _get_router_mac() method

### ISSUE THREAD

**Issue by yxieca** [sonic-net/sonic-mgmt#23695]
### Description

`tests/decap/test_subnet_decap.py` (introduced by PR #17269) calls `duthost._get_router_mac()` in 6 places. This private method was removed by PR #21442 which refactored `SonicHost` facts initialization. The two PRs were developed in parallel and the conflict was not caught during review.

### Steps to Reproduce

Run any test in `tests/decap/test_subnet_decap.py`:
```
pytest tests/decap/test_subnet_decap.py
```

### Expected Behavior

Tests execute successfully.

### Actual Behavior

```
AttributeError: '<class tests.common.devices.sonic.SonicHost>' object has no attribute '_get_router_mac'
```

### Fix

PR #23694 replaces all 6 occurrences with `duthost.facts["router_mac"]`.

### Platform

All platforms.

### Severity

High - all subnet decap tests are broken on current master.
