### ISSUE TITLE
Bug: test_qos_probe.py TypeError on T2 KVM — SonicAsic.command() rejects module_ignore_errors

### ISSUE THREAD

**Issue by yxieca** [sonic-net/sonic-mgmt#24069]
### Is it platform specific
generic

### Importance or Severity
High

### Description of the bug
`test_qos_probe.py` (introduced in PR #22547) fails with `TypeError` on **T2 KVM testbed** (`vms-kvm-t2`) during the `stopServices` fixture.

The `updateFeatureState()` helper in `qos_sai_base.py:1654` calls `host.command(..., module_ignore_errors=True)`. When `host` is a `SonicAsic` object (which happens on T2 multi-DUT topologies with the `multi_dut_longlink_to_shortlink` parametrize), the call fails because `SonicAsic.command()` does not accept `module_ignore_errors` as a keyword argument — only `MultiAsicSonicHost.command()` does.

**Cascading failure:** After `stopServices` crashes, the teardown attempts `config_reload` but critical services never fully restart (LLDP/BGP were partially disabled), causing a 15-minute timeout and `Failed: All critical services should be fully started!`.

**Affected parametrize:** `[multi_dut_longlink_to_shortlink-xoff_1]` — `dst_asic` is `SonicAsic 1` on `vlab-t2-1-2`.

### Steps to Reproduce
1. Run on T2 KVM testbed:
```
python3 -m pytest qos/test_qos_probe.py --testbed=vms-kvm-t2 --testbed_file=../ansible/vtestbed.yaml --device_type=vs --maxfail=1
```

### Actual Behavior and Expected Behavior
**Actual:** `TypeError: SonicAsic.command() got an unexpected keyword argument 'module_ignore_errors'` at `qos_sai_base.py:1654`

**Expected:** `updateFeatureState()` should use `SonicAsic`-compatible API, e.g. `host.sonichost.command(..., module_ignore_errors=True)` or use `shell()` instead.

### Relevant log output
```
qos/qos_sai_base.py:1729: in stopServices
    updateFeatureState(dst_asic, "lldp", "enabled")
qos/qos_sai_base.py:1654: in updateFeatureState
    host.command(
        "sudo config feature state {feature} {state}".format(feature=feature, state=state),
        module_ignore_errors=True
    )
TypeError: SonicAsic.command() got an unexpected keyword argument 'module_ignore_errors'

Variables:
  host = <SonicAsic 1>
  feature = 'lldp'
  state = 'enabled'
  dst_dut = <MultiAsicSonicHost vlab-t2-1-2>
```

### Output of `show version`
KVM VS virtual switch (T2 multi-DUT multi-ASIC topology)

### Attach files (if any)
Introduced by PR #22547. Note: T2 also hits a separate port count issue (#23988).

**Comment by yxieca** [comment]
**RCA Correction:** Same as #24068 — the root cause of this failure surfacing in CI is that issue #22599 was **closed ~4 days ago**, disabling the conditional_mark skip for all VS KVM testbeds. The underlying `SonicAsic.command()` bug was always there but was masked by the skip.

Issue #22599 has been reopened, restoring skip protection. The code bug still needs fixing.

🤖 *This response was generated by an AI agent on behalf of @yxieca.*

**Comment by yxieca** [comment]
Closing — same root cause as #24068. CI failures were caused by #22599 being closed. #22599 has been reopened.
