### ISSUE TITLE
[advanced_reboot] test_warm_reboot - 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by AntonHryshchuk** [sonic-net/sonic-mgmt#5864]
**Description**
Test issue in warm-reboot test run.
Instead of a clean reason for what happened, the test raised the error of "object has no attribute".
Introduced by #5699. Without the change a test warm-reboot passed.

**Steps to reproduce the issue:**
1. run test     platform_tests/test_advanced_reboot.py::test_warm_reboot

**Describe the results you received:**
The parameter **apply_view** is empty. Before the change this parameter is not empty.

```
test failed on the test issue:
    def verify_required_events(duthost, event_counters, timing_data, verification_errors):
        for key in ["time_span", "offset_from_kexec"]:
            for pattern in REQUIRED_PATTERNS.get(key):
>               observed_start_count = timing_data.get(key).get(pattern).get("Start count")
E               AttributeError: 'NoneType' object has no attribute 'get'
key        = 'time_span'
pattern    = 'APPLY_VIEW'
```
```
"time_span": {
        "radv": "56.702367", 
        "bgp": "45.862906", 
        "syncd": "28.891664", 
        "swss": "", 
        "teamd": "30.890066", 
        "database": "19.710746", 
        "syncd_create_switch": "4.282026", 
        "sai_create_switch": "6.318191", 
        "apply_view": "", 
        "init_view": "0.140149", 
        "neighbor_entry": "239.901838", 
        "port_init": "2.418577", 
        "port_ready": "", 
        "finalizer": "136.571938", 
        "lag_ready": "0.007785", 
        "fpmsyncd_reconciliation": "", 
        "route_deferral_timer": "0.487191", 
        "fdb_restore": "1.02116"
    }
```

**Describe the results you expected:**
Test passed

**Comment by AharonMalkin** [comment]
Fixed in [Fixed observed counter logic and PORT_READY event capturing in advanced reboot tests #7206](https://github.com/sonic-net/sonic-mgmt/pull/7206)
Closing.
